type: edu
files:
- name: src/Task.java
  visible: true
  placeholders:
  - offset: 143
    length: 12
    placeholder_text: // type here
    initial_state:
      length: 12
      offset: 143
    initialized_from_dependency: false
    selected: false
    status: Unchecked
    encrypted_possible_answer: |2
              String text = scanner.nextLine();
              text = text.replaceAll(" ", "");    // removes spaces
              text = text.toLowerCase();     // palindromes are case insensitive

              boolean palindrome = true;
              for (int i = 0; i < text.length() / 2; i++) {
                  if (text.charAt(i) != text.charAt(text.length() - 1 - i)) {
                      palindrome = false;
                      break;
                  }
              }
              System.out.println(palindrome);

              // Alternative for iteration sign-by-sign is to reverse text String
              String textReverse = new StringBuilder(text).reverse().toString();
              //System.out.println(text.equals(textReverse));
  text: |-
    import java.util.Scanner;

    public class Task {
        public static void main(String[] args) {
            Scanner scanner = new Scanner(System.in);

    // type here
        }
    }
  learner_created: false
- name: test/BaseTest.java
  visible: false
  text: |
    import org.junit.After;

    import java.io.ByteArrayInputStream;
    import java.io.ByteArrayOutputStream;
    import java.io.PrintStream;
    import java.util.function.Consumer;

    import static org.junit.Assert.assertEquals;

    public class BaseTest {

        @After
        public void restoreStreams() {
            System.setOut(System.out);
            System.setIn(System.in);
        }

        protected void runTest(String input, String expected) {
            String actual = run(Task::main, input);

            assertEquals("Wrong answer for following input: \n" + input + "\n", expected, actual);
        }

        private String run(Consumer<String[]> method, String input) {
            System.setIn(new ByteArrayInputStream(input.getBytes()));

            ByteArrayOutputStream outContent = new ByteArrayOutputStream();
            System.setOut(new PrintStream(outContent));

            method.accept(new String[]{});
            return outContent.toString().trim();
        }
    }
  learner_created: false
- name: test/Tests.java
  visible: false
  text: |-
    import org.junit.Test;

    public class Tests extends BaseTest {

        @Test
        public void testSolution() {
            runTest("kayak", "true");
        }

        @Test
        public void testSolution2() {
            runTest("Ka yak", "true");
        }

        @Test
        public void testSolution3() {
            runTest("abccba", "true");
        }

        @Test
        public void testSolution4() {
            runTest("ab bc", "false");
        }

        @Test
        public void testSolution5() {
            runTest("ab ca", "false");
        }

    }
  learner_created: false
status: Unchecked
record: -1
